Traceback (most recent call last):
  File "c:\users\mi\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\mi\anaconda3\lib\site-packages\nbclient\client.py", line 1082, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\mi\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\mi\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\mi\anaconda3\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\users\mi\anaconda3\lib\site-packages\nbclient\client.py", line 536, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\mi\anaconda3\lib\site-packages\nbclient\client.py", line 827, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\mi\anaconda3\lib\site-packages\nbclient\client.py", line 735, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Given data
data19 = pd.read_csv("T06_P19_data.csv", sep=",", header=None)
d19_tm = np.array(data19[0])
d19_s = np.array(data19[1])
d19 = {"Time [min]":d19_tm, "Drawdown [m]":d19_s}
df19 = pd.DataFrame(d19)

r = 251.32
t19_s = d19_tm * 60
t19_r2 = t19_s / r**2
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
[1;32m<ipython-input-13-50e4b40aa160>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m#Given data[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 2[1;33m [0mdata19[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mread_csv[0m[1;33m([0m[1;34m"T06_P19_data.csv"[0m[1;33m,[0m [0msep[0m[1;33m=[0m[1;34m","[0m[1;33m,[0m [0mheader[0m[1;33m=[0m[1;32mNone[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      3[0m [0md19_tm[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0marray[0m[1;33m([0m[0mdata19[0m[1;33m[[0m[1;36m0[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m [0md19_s[0m [1;33m=[0m [0mnp[0m[1;33m.[0m[0marray[0m[1;33m([0m[0mdata19[0m[1;33m[[0m[1;36m1[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [0md19[0m [1;33m=[0m [1;33m{[0m[1;34m"Time [min]"[0m[1;33m:[0m[0md19_tm[0m[1;33m,[0m [1;34m"Drawdown [m]"[0m[1;33m:[0m[0md19_s[0m[1;33m}[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\parsers.py[0m in [0;36mparser_f[1;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)[0m
[0;32m    674[0m         )
[0;32m    675[0m [1;33m[0m[0m
[1;32m--> 676[1;33m         [1;32mreturn[0m [0m_read[0m[1;33m([0m[0mfilepath_or_buffer[0m[1;33m,[0m [0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    677[0m [1;33m[0m[0m
[0;32m    678[0m     [0mparser_f[0m[1;33m.[0m[0m__name__[0m [1;33m=[0m [0mname[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\parsers.py[0m in [0;36m_read[1;34m(filepath_or_buffer, kwds)[0m
[0;32m    446[0m [1;33m[0m[0m
[0;32m    447[0m     [1;31m# Create the parser.[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 448[1;33m     [0mparser[0m [1;33m=[0m [0mTextFileReader[0m[1;33m([0m[0mfp_or_buf[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    449[0m [1;33m[0m[0m
[0;32m    450[0m     [1;32mif[0m [0mchunksize[0m [1;32mor[0m [0miterator[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\parsers.py[0m in [0;36m__init__[1;34m(self, f, engine, **kwds)[0m
[0;32m    878[0m             [0mself[0m[1;33m.[0m[0moptions[0m[1;33m[[0m[1;34m"has_index_names"[0m[1;33m][0m [1;33m=[0m [0mkwds[0m[1;33m[[0m[1;34m"has_index_names"[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m    879[0m [1;33m[0m[0m
[1;32m--> 880[1;33m         [0mself[0m[1;33m.[0m[0m_make_engine[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mengine[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    881[0m [1;33m[0m[0m
[0;32m    882[0m     [1;32mdef[0m [0mclose[0m[1;33m([0m[0mself[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\parsers.py[0m in [0;36m_make_engine[1;34m(self, engine)[0m
[0;32m   1112[0m     [1;32mdef[0m [0m_make_engine[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mengine[0m[1;33m=[0m[1;34m"c"[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1113[0m         [1;32mif[0m [0mengine[0m [1;33m==[0m [1;34m"c"[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 1114[1;33m             [0mself[0m[1;33m.[0m[0m_engine[0m [1;33m=[0m [0mCParserWrapper[0m[1;33m([0m[0mself[0m[1;33m.[0m[0mf[0m[1;33m,[0m [1;33m**[0m[0mself[0m[1;33m.[0m[0moptions[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1115[0m         [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1116[0m             [1;32mif[0m [0mengine[0m [1;33m==[0m [1;34m"python"[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\lib\site-packages\pandas\io\parsers.py[0m in [0;36m__init__[1;34m(self, src, **kwds)[0m
[0;32m   1889[0m         [0mkwds[0m[1;33m[[0m[1;34m"usecols"[0m[1;33m][0m [1;33m=[0m [0mself[0m[1;33m.[0m[0musecols[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1890[0m [1;33m[0m[0m
[1;32m-> 1891[1;33m         [0mself[0m[1;33m.[0m[0m_reader[0m [1;33m=[0m [0mparsers[0m[1;33m.[0m[0mTextReader[0m[1;33m([0m[0msrc[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   1892[0m         [0mself[0m[1;33m.[0m[0munnamed_cols[0m [1;33m=[0m [0mself[0m[1;33m.[0m[0m_reader[0m[1;33m.[0m[0munnamed_cols[0m[1;33m[0m[1;33m[0m[0m
[0;32m   1893[0m [1;33m[0m[0m

[1;32mpandas\_libs\parsers.pyx[0m in [0;36mpandas._libs.parsers.TextReader.__cinit__[1;34m()[0m

[1;32mpandas\_libs\parsers.pyx[0m in [0;36mpandas._libs.parsers.TextReader._setup_parser_source[1;34m()[0m

[1;31mFileNotFoundError[0m: [Errno 2] File T06_P19_data.csv does not exist: 'T06_P19_data.csv'
FileNotFoundError: [Errno 2] File T06_P19_data.csv does not exist: 'T06_P19_data.csv'

